import '../page.module.css'
import 'bootstrap/dist/css/bootstrap.css';
import NavBar from '../components/NavBar';

// `app/page.tsx` is the UI for the `/` URL
export default function Page() {
    return (
        <>
            
            <h1>Hello, Home page!</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consequat id porta nibh venenatis. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget. Nec ultrices dui sapien eget mi proin sed. Dignissim sodales ut eu sem integer. Vel eros donec ac odio. Sit amet est placerat in egestas erat imperdiet sed euismod. Justo laoreet sit amet cursus. Ut tristique et egestas quis. A cras semper auctor neque vitae tempus. Sed augue lacus viverra vitae congue eu consequat. Pharetra massa massa ultricies mi. Et leo duis ut diam quam nulla porttitor massa id. Risus nullam eget felis eget nunc. Est lorem ipsum dolor sit amet consectetur. Quis commodo odio aenean sed adipiscing diam donec adipiscing.</p><p>

            Sed vulputate odio ut enim blandit volutpat maecenas. Et tortor at risus viverra adipiscing at in tellus integer. Mattis rhoncus urna neque viverra. Ac auctor augue mauris augue neque gravida in. Lacus laoreet non curabitur gravida arcu ac tortor dignissim. Lacinia quis vel eros donec ac odio. Mauris cursus mattis molestie a iaculis. Tincidunt arcu non sodales neque. Id venenatis a condimentum vitae sapien pellentesque habitant. Id donec ultrices tincidunt arcu. Aliquet lectus proin nibh nisl condimentum id venenatis a. Amet nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Sed felis eget velit aliquet sagittis id consectetur purus ut. Sem fringilla ut morbi tincidunt augue interdum. Velit dignissim sodales ut eu sem integer vitae justo eget. Tristique et egestas quis ipsum suspendisse. Hac habitasse platea dictumst quisque sagittis. Aliquet bibendum enim facilisis gravida neque convallis a cras semper. Feugiat nisl pretium fusce id.</p><p>

            Tellus id interdum velit laoreet id donec ultrices. Enim nec dui nunc mattis enim ut. Quam viverra orci sagittis eu volutpat odio facilisis mauris. Pellentesque diam volutpat commodo sed egestas egestas fringilla. Fermentum dui faucibus in ornare quam viverra orci sagittis eu. Morbi non arcu risus quis varius. Vitae semper quis lectus nulla at volutpat diam. Diam ut venenatis tellus in metus vulputate eu. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Nunc sed id semper risus. Aliquet lectus proin nibh nisl. Neque volutpat ac tincidunt vitae semper quis lectus nulla. Pharetra magna ac placerat vestibulum lectus mauris. Volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque.</p><p>

            Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Ut tristique et egestas quis ipsum suspendisse ultrices gravida dictum. Iaculis eu non diam phasellus vestibulum. Nulla pharetra diam sit amet nisl suscipit adipiscing bibendum est. Lectus arcu bibendum at varius vel pharetra vel turpis nunc. Hendrerit dolor magna eget est lorem ipsum dolor. Ipsum consequat nisl vel pretium lectus quam id leo. Tortor at risus viverra adipiscing at in. Egestas congue quisque egestas diam. Vivamus arcu felis bibendum ut. Volutpat odio facilisis mauris sit amet massa vitae. Tincidunt id aliquet risus feugiat. Pellentesque id nibh tortor id aliquet lectus proin nibh nisl. A pellentesque sit amet porttitor eget dolor morbi non arcu. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices. Lectus magna fringilla urna porttitor rhoncus dolor purus non enim. Tincidunt arcu non sodales neque sodales ut.</p><p>

            Sed libero enim sed faucibus. Pulvinar mattis nunc sed blandit libero volutpat. Nibh ipsum consequat nisl vel pretium lectus quam. Sit amet consectetur adipiscing elit duis. Pharetra sit amet aliquam id diam maecenas ultricies mi eget. Nunc vel risus commodo viverra maecenas accumsan lacus vel. At in tellus integer feugiat scelerisque varius morbi. Suscipit tellus mauris a diam maecenas sed enim ut. Risus sed vulputate odio ut enim blandit. Sed arcu non odio euismod. Ullamcorper eget nulla facilisi etiam dignissim diam. Praesent elementum facilisis leo vel fringilla est ullamcorper. At augue eget arcu dictum varius.
            </p><p>
            Fringilla urna porttitor rhoncus dolor purus non. Non nisi est sit amet. Adipiscing vitae proin sagittis nisl rhoncus. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Non pulvinar neque laoreet suspendisse interdum consectetur libero id. Id aliquet risus feugiat in ante metus dictum. Vitae elementum curabitur vitae nunc sed velit dignissim sodales. Id faucibus nisl tincidunt eget. Sed adipiscing diam donec adipiscing tristique. Urna porttitor rhoncus dolor purus non enim praesent elementum. Ac turpis egestas integer eget. Arcu risus quis varius quam. Tempus imperdiet nulla malesuada pellentesque elit eget. Tristique sollicitudin nibh sit amet commodo nulla facilisi. Malesuada proin libero nunc consequat interdum varius sit amet mattis. Adipiscing elit ut aliquam purus sit. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere. Amet dictum sit amet justo donec enim. Viverra nam libero justo laoreet sit amet.
            </p><p>
            Morbi non arcu risus quis varius quam quisque id diam. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Sit amet nisl purus in mollis. Scelerisque eu ultrices vitae auctor. Nullam vehicula ipsum a arcu cursus vitae. Maecenas sed enim ut sem viverra. Eu ultrices vitae auctor eu augue ut lectus arcu bibendum. Nunc mi ipsum faucibus vitae. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Morbi tempus iaculis urna id volutpat lacus. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien. Id aliquet risus feugiat in. Condimentum vitae sapien pellentesque habitant morbi tristique. Lectus urna duis convallis convallis tellus id interdum. Vestibulum lectus mauris ultrices eros. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc consequat. Id faucibus nisl tincidunt eget nullam non. Risus nullam eget felis eget nunc.
            </p><p>
            At risus viverra adipiscing at in. Pellentesque elit eget gravida cum sociis natoque. In massa tempor nec feugiat nisl. Maecenas accumsan lacus vel facilisis. Eu lobortis elementum nibh tellus molestie. Velit euismod in pellentesque massa placerat duis ultricies lacus. Vel facilisis volutpat est velit egestas dui id ornare arcu. Pretium nibh ipsum consequat nisl. Diam quam nulla porttitor massa id neque aliquam. Libero nunc consequat interdum varius sit amet mattis vulputate.
            </p><p>
            Mattis molestie a iaculis at erat pellentesque adipiscing commodo elit. Varius duis at consectetur lorem. At in tellus integer feugiat scelerisque varius. Magnis dis parturient montes nascetur ridiculus mus. Vel orci porta non pulvinar neque laoreet suspendisse interdum. Adipiscing enim eu turpis egestas pretium aenean pharetra magna ac. Velit euismod in pellentesque massa placerat duis ultricies. Ac felis donec et odio pellentesque diam volutpat commodo sed. Nibh mauris cursus mattis molestie a iaculis. Blandit aliquam etiam erat velit scelerisque in dictum non. Malesuada proin libero nunc consequat interdum varius. Vivamus at augue eget arcu dictum varius duis at consectetur. Velit scelerisque in dictum non consectetur. Donec adipiscing tristique risus nec feugiat in fermentum posuere. Nec nam aliquam sem et tortor consequat id porta nibh. Interdum varius sit amet mattis vulputate enim nulla aliquet porttitor. Velit scelerisque in dictum non consectetur a. Scelerisque in dictum non consectetur a. Eget aliquet nibh praesent tristique magna.
            </p><p>
            Odio ut sem nulla pharetra diam sit amet. Morbi tincidunt ornare massa eget egestas purus. Volutpat blandit aliquam etiam erat velit scelerisque in dictum non. Placerat duis ultricies lacus sed turpis tincidunt. Eget dolor morbi non arcu risus. Vel risus commodo viverra maecenas accumsan lacus. Cursus vitae congue mauris rhoncus aenean vel elit. Ipsum dolor sit amet consectetur adipiscing elit. Sit amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Sit amet aliquam id diam. Dui id ornare arcu odio ut sem nulla pharetra diam. Vulputate ut pharetra sit amet. Aliquam etiam erat velit scelerisque. Varius quam quisque id diam vel quam elementum pulvinar etiam. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Nibh praesent tristique magna sit amet. Senectus et netus et malesuada fames ac. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. In est ante in nibh mauris cursus mattis molestie a. Et egestas quis ipsum suspendisse ultrices gravida dictum.</p><p>
            At risus viverra adipiscing at in. Pellentesque elit eget gravida cum sociis natoque. In massa tempor nec feugiat nisl. Maecenas accumsan lacus vel facilisis. Eu lobortis elementum nibh tellus molestie. Velit euismod in pellentesque massa placerat duis ultricies lacus. Vel facilisis volutpat est velit egestas dui id ornare arcu. Pretium nibh ipsum consequat nisl. Diam quam nulla porttitor massa id neque aliquam. Libero nunc consequat interdum varius sit amet mattis vulputate.
            </p><p>
            Mattis molestie a iaculis at erat pellentesque adipiscing commodo elit. Varius duis at consectetur lorem. At in tellus integer feugiat scelerisque varius. Magnis dis parturient montes nascetur ridiculus mus. Vel orci porta non pulvinar neque laoreet suspendisse interdum. Adipiscing enim eu turpis egestas pretium aenean pharetra magna ac. Velit euismod in pellentesque massa placerat duis ultricies. Ac felis donec et odio pellentesque diam volutpat commodo sed. Nibh mauris cursus mattis molestie a iaculis. Blandit aliquam etiam erat velit scelerisque in dictum non. Malesuada proin libero nunc consequat interdum varius. Vivamus at augue eget arcu dictum varius duis at consectetur. Velit scelerisque in dictum non consectetur. Donec adipiscing tristique risus nec feugiat in fermentum posuere. Nec nam aliquam sem et tortor consequat id porta nibh. Interdum varius sit amet mattis vulputate enim nulla aliquet porttitor. Velit scelerisque in dictum non consectetur a. Scelerisque in dictum non consectetur a. Eget aliquet nibh praesent tristique magna.
            </p><p>
            Odio ut sem nulla pharetra diam sit amet. Morbi tincidunt ornare massa eget egestas purus. Volutpat blandit aliquam etiam erat velit scelerisque in dictum non. Placerat duis ultricies lacus sed turpis tincidunt. Eget dolor morbi non arcu risus. Vel risus commodo viverra maecenas accumsan lacus. Cursus vitae congue mauris rhoncus aenean vel elit. Ipsum dolor sit amet consectetur adipiscing elit. Sit amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Sit amet aliquam id diam. Dui id ornare arcu odio ut sem nulla pharetra diam. Vulputate ut pharetra sit amet. Aliquam etiam erat velit scelerisque. Varius quam quisque id diam vel quam elementum pulvinar etiam. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Nibh praesent tristique magna sit amet. Senectus et netus et malesuada fames ac. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. In est ante in nibh mauris cursus mattis molestie a. Et egestas quis ipsum suspendisse ultrices gravida dictum.</p><p>
            At risus viverra adipiscing at in. Pellentesque elit eget gravida cum sociis natoque. In massa tempor nec feugiat nisl. Maecenas accumsan lacus vel facilisis. Eu lobortis elementum nibh tellus molestie. Velit euismod in pellentesque massa placerat duis ultricies lacus. Vel facilisis volutpat est velit egestas dui id ornare arcu. Pretium nibh ipsum consequat nisl. Diam quam nulla porttitor massa id neque aliquam. Libero nunc consequat interdum varius sit amet mattis vulputate.
            </p><p>
            Mattis molestie a iaculis at erat pellentesque adipiscing commodo elit. Varius duis at consectetur lorem. At in tellus integer feugiat scelerisque varius. Magnis dis parturient montes nascetur ridiculus mus. Vel orci porta non pulvinar neque laoreet suspendisse interdum. Adipiscing enim eu turpis egestas pretium aenean pharetra magna ac. Velit euismod in pellentesque massa placerat duis ultricies. Ac felis donec et odio pellentesque diam volutpat commodo sed. Nibh mauris cursus mattis molestie a iaculis. Blandit aliquam etiam erat velit scelerisque in dictum non. Malesuada proin libero nunc consequat interdum varius. Vivamus at augue eget arcu dictum varius duis at consectetur. Velit scelerisque in dictum non consectetur. Donec adipiscing tristique risus nec feugiat in fermentum posuere. Nec nam aliquam sem et tortor consequat id porta nibh. Interdum varius sit amet mattis vulputate enim nulla aliquet porttitor. Velit scelerisque in dictum non consectetur a. Scelerisque in dictum non consectetur a. Eget aliquet nibh praesent tristique magna.
            </p><p>
            Odio ut sem nulla pharetra diam sit amet. Morbi tincidunt ornare massa eget egestas purus. Volutpat blandit aliquam etiam erat velit scelerisque in dictum non. Placerat duis ultricies lacus sed turpis tincidunt. Eget dolor morbi non arcu risus. Vel risus commodo viverra maecenas accumsan lacus. Cursus vitae congue mauris rhoncus aenean vel elit. Ipsum dolor sit amet consectetur adipiscing elit. Sit amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Sit amet aliquam id diam. Dui id ornare arcu odio ut sem nulla pharetra diam. Vulputate ut pharetra sit amet. Aliquam etiam erat velit scelerisque. Varius quam quisque id diam vel quam elementum pulvinar etiam. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Nibh praesent tristique magna sit amet. Senectus et netus et malesuada fames ac. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. In est ante in nibh mauris cursus mattis molestie a. Et egestas quis ipsum suspendisse ultrices gravida dictum.</p>
        </>
    )
}